### ISSUE TITLE
XMLFacets: Eag Persons are not facetted [JIRA CVRE-178]

### ISSUE THREAD

**Issue by cendarijiraimpert** [CENDARI/editorsnotes#179]
On productive XMLFacets search no facets are created for creators which are structured in EAG or EAD files.
Also there are no facets for contributors or persons.
I am wondering what is the difference between all

reported by NatasaBulatovic on 2015-07-17T00:47:32.169+0200

**Comment by schildwaechter** [comment]
XMLFacets is no longer supported.

Jean-DanielFekete on 2015-12-14T18:58:46.406+0100
